"""add link collumn to groups table

Revision ID: 5617d3bcae33
Revises: 333f7f6280e4
Create Date: 2022-12-04 00:46:45.000861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5617d3bcae33'
down_revision = '333f7f6280e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('link', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'link')
    # ### end Alembic commands ###
