version: '3'

services:
  bot:
    image: python:3.10
    container_name: bot
    build:
      dockerfile: Dockerfile
    working_dir: /usr/src/app/
    volumes:
      - .:/usr/src/app/
    command: python3 main.py
    restart: always
    depends_on:
      - db
    env_file: .env
    network_mode: host

  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}

    container_name: db
    env_file: .env
    ports:
      - 5432:5432
    expose:
      - 5432

volumes:
  postgres_data:
